---
- name: Use a secret from HCP Vault
  hosts: vault
  connection: local
  vars:
    vault_url: http://{{ ansible_host }}:8200
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name: python3-hvac

    - name: Check if the vault variables are defined.
      ansible.builtin.assert:
        that:
          - vault_role_id is defined
          - vault_secret_id is defined

    - name: Login to vault to get token
      community.hashi_vault.vault_login:
        url: "{{ vault_url }}"
        auth_method: approle
        role_id: "{{ vault_role_id }}"
        secret_id: "{{ vault_secret_id }}"
      register: login_result

    - name: Read secret
      community.hashi_vault.vault_kv2_get:
        url: "{{ vault_url }}"
        auth_method: token
        token: '{{ login_result.login.auth.client_token }}'
        path: "secret/db_password"
      register: vault_get_result

    - name: Set var to secret
      ansible.builtin.set_fact:
        db_password: "{{ vault_get_result.secret.db_password }}"

    - name: Display secret
      ansible.builtin.debug:
        msg: "db_password = {{ db_password }}"
