---
- name: Install vault
  hosts: vault
  gather_facts: false
  vars:
    vault_version: "1.9.0"
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - unzip
        state: present

    - name: Download Vault binary
      ansible.builtin.get_url:
        url: https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip
        dest: /tmp/vault_{{ vault_version }}_linux_amd64.zip
        mode: "0644"

    - name: Unzip the Vault binary
      ansible.builtin.unarchive:
        src: /tmp/vault_{{ vault_version }}_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: true
        creates: /usr/local/bin/vault

    - name: Set Vault binary executable
      ansible.builtin.file:
        path: /usr/local/bin/vault
        mode: "0755"

    - name: Create Vault config directory
      ansible.builtin.file:
        path: /etc/vault.d
        state: directory
        mode: "0755"

    - name: Deploy Vault configuration file
      ansible.builtin.template:
        src: etc/vault.d/vault.hcl.j2
        dest: /etc/vault.d/vault.hcl
        mode: "0644"

    - name: Create Vault data directory
      ansible.builtin.file:
        path: /opt/vault/data
        state: directory
        mode: "0755"

    - name: Create Vault service file
      ansible.builtin.copy:
        dest: /etc/systemd/system/vault.service
        content: |
          [Unit]
          Description=Vault
          Requires=network-online.target
          After=network-online.target

          [Service]
          User=root
          Group=root
          ProtectSystem=full
          ExecStart=/usr/local/bin/vault server -config=/etc/vault.d/vault.hcl
          ExecReload=/bin/kill -HUP $MAINPID
          KillMode=process
          Restart=on-failure
          LimitNOFILE=65536

          [Install]
          WantedBy=multi-user.target
        mode: "0644"

    - name: Enable and start Vault service
      ansible.builtin.systemd:
        name: vault
        enabled: true
        state: started
