---
- name: Install vault
  hosts: vault
  gather_facts: false
  vars:
    vault_version: "1.16.2"
    vault_group: vault
    vault_user: vault
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - unzip
        state: present

    - name: Creating vault user group
      ansible.builtin.group:
        name: "{{ vault_group }}"

    - name: Creating vault user
      ansible.builtin.user:
        name: "{{ vault_user }}"
        group: "{{ vault_group }}"
        system: true
        shell: "/sbin/nologin"
        comment: "vault nologin user"
        createhome: "no"
        state: present

    - name: Download Vault binary
      ansible.builtin.get_url:
        url: https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip
        dest: /root/vault_{{ vault_version }}_linux_amd64.zip
        mode: "0644"

    - name: Unzip the Vault binary
      ansible.builtin.unarchive:
        src: /root/vault_{{ vault_version }}_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: true
        creates: /usr/local/bin/vault

    - name: Set Vault binary executable
      ansible.builtin.file:
        path: /usr/local/bin/vault
        owner: "{{ vault_user }}"
        group: "{{ vault_group }}"
        mode: "0755"

    - name: Set vault binary capabilities
      community.general.capabilities:
        path: /usr/local/bin/vault
        capability: cap_ipc_lock=ep
        state: present
      tags: caps

    - name: Create Vault config directory
      ansible.builtin.file:
        path: /etc/vault.d
        state: directory
        owner: "{{ vault_user }}"
        group: "{{ vault_group }}"
        mode: "0755"

    - name: Deploy Vault configuration file
      ansible.builtin.template:
        src: etc/vault.d/vault.hcl.j2
        dest: /etc/vault.d/vault.hcl
        owner: "{{ vault_user }}"
        group: "{{ vault_group }}"
        mode: "0644"
      notify: Reload vault

    - name: Create Vault data directory
      ansible.builtin.file:
        path: /opt/vault/data
        state: directory
        owner: "{{ vault_user }}"
        group: "{{ vault_group }}"
        mode: "0755"

    - name: Create Vault service file
      ansible.builtin.template:
        src: etc/systemd/system/vault.service.j2
        dest: /etc/systemd/system/vault.service
        owner: root
        group: root
        mode: "0644"

    - name: Enable and start Vault service
      ansible.builtin.systemd:
        name: vault
        enabled: true
        state: started

    - name: Set proper vault address for all users
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: VAULT_ADDR=http://127.0.0.1:8200

    - name: Check vault status
      ansible.builtin.command:
        cmd: vault status
      register: vault_status_result
      failed_when: false
      changed_when: false

    - name: Assert vault status succeeded
      ansible.builtin.assert:
        that: vault_status_result.rc == 2 or vault_status_result.rc == 2

  handlers:
    - name: Reload vault
      ansible.builtin.service:
        name: vault
        state: reloaded
