---
- name: Enable the specified engine
  tags: secrets-engines
  block:
    - name: Check loop variables
      ansible.builtin.assert:
        that:
          - engine is defined
          - engine.full_name is defined
          - engine.name is defined
          - engine.root is defined

    - name: Check secrets engines
      ansible.builtin.command:
        cmd: vault secrets list
      environment:
        VAULT_TOKEN: "{{ vault_token }}"
      register: vault_secrets_list_result
      changed_when: false

    - name: Enable secrets engine {{ engine.full_name }}
      ansible.builtin.command:
        cmd: vault secrets enable -path={{ engine.root }} {{ engine.full_name }}
      environment:
        VAULT_TOKEN: "{{ vault_token }}"
      changed_when: true
      when: vault_secrets_list_result is not regex(engine.root ~ '/\s+' ~ engine.name)
